remote_theme: pages-themes/slate@v0.2.0
plugins:
- jekyll-remote-theme
title: [Recursos para o Livro Arquitetura e Organização de Computadores]
description: [Gabriel P. Silva & José Antonio S. Borges -- Editora LTC]
