remote_theme: pages-themes/slate@v0.2.0
plugins:
- jekyll-remote-theme
title: [Simulador SimuS do Livro Arquitetura e Organização de Computadores]
description: [Recursos para o Livro Arquitetura e Organização de Computadores]
